apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-db-pvc
  namespace: banking-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: customer-db-secret
  namespace: banking-system
type: Opaque
data:
  POSTGRES_USER: Y3VzdG9tZXJfdXNlcg==
  POSTGRES_PASSWORD: Y3VzdG9tZXJfcGFzcw==
  POSTGRES_DB: Y3VzdG9tZXJfZGI=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db
  namespace: banking-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-db
  template:
    metadata:
      labels:
        app: customer-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: customer-db-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "customer_user", "-d", "customer_db"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "customer_user", "-d", "customer_db"]
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: customer-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: customer-db
  namespace: banking-system
spec:
  selector:
    app: customer-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
